package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fail("resolve repo root: %v", err)
	}
	soundDir := filepath.Join(repoRoot, "resources", "sound")
	entries, err := os.ReadDir(soundDir)
	if err != nil {
		fail("read sound dir %q: %v", soundDir, err)
	}

	type soundFile struct {
		name string
		data []byte
	}
	sounds := make([]soundFile, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(strings.ToLower(name), ".wav") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(soundDir, name))
		if err != nil {
			fail("read %q: %v", name, err)
		}
		sounds = append(sounds, soundFile{name: name, data: content})
	}
	sort.Slice(sounds, func(i, j int) bool { return sounds[i].name < sounds[j].name })
	if len(sounds) == 0 {
		fail("no .wav files found in %q", soundDir)
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by bridge/cmd/embed-sounds. DO NOT EDIT.\n")
	out.WriteString("package main\n\n")
	out.WriteString("var embeddedSounds = map[string][]byte{\n")
	for _, snd := range sounds {
		fmt.Fprintf(&out, "\t%q: []byte{", snd.name)
		for i, b := range snd.data {
			if i%16 == 0 {
				out.WriteString("\n\t\t")
			}
			fmt.Fprintf(&out, "0x%02x, ", b)
		}
		out.WriteString("\n\t},\n")
	}
	out.WriteString("}\n")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fail("format generated file: %v", err)
	}
	target := filepath.Join(repoRoot, "bridge", "sounds_generated.go")
	if err := os.WriteFile(target, formatted, 0o644); err != nil {
		fail("write %q: %v", target, err)
	}
	fmt.Printf("Generated %s with %d embedded wav files.\n", target, len(sounds))
}

func findRepoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	cur := wd
	for {
		if pathExists(filepath.Join(cur, "resources", "sound")) &&
			pathExists(filepath.Join(cur, "bridge")) {
			return cur, nil
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			break
		}
		cur = parent
	}
	return "", fmt.Errorf("could not find repository root from %q", wd)
}

func pathExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func fail(msg string, args ...any) {
	fmt.Fprintf(os.Stderr, msg+"\n", args...)
	os.Exit(1)
}
